name: Build and push Docker image to GHCR

on:
  release:
    types: [published]
  workflow_dispatch:
env:
  CURRENT_VERSION: "v0.7.0"
  BUILD_NUMBER: "0"
  IMAGE_NAME: "jwilder--dockerize"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.GITHUB_REPOSITORY_OWNER }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.REPOSITORY_OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: >
            ghcr.io/${{ github.REPOSITORY_OWNER }}/${{ env.IMAGE_NAME }}:latest,
            ghcr.io/${{ github.REPOSITORY_OWNER }}/${{ env.IMAGE_NAME }}:${{ env.CURRENT_VERSION }},
            ghcr.io/${{ github.REPOSITORY_OWNER }}/${{ env.IMAGE_NAME }}:${{ env.CURRENT_VERSION }}-r$${{ env.BUILD_NUMBER }},
